# Generated by Django 4.0.3 on 2022-03-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/Doctor'),
        ),
    ]
