# Generated by Django 4.0.3 on 2022-04-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_describe_doctor_specualization'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='activate',
            field=models.BooleanField(default=False),
        ),
    ]
